### PR TITLE
Ambiant-Mate: increase height of menuitems

### PR DESCRIPTION
**Pull request by raveit65**
Height of all menuitems are increased, please test.

### CODE REVIEW

**Comment by raveit65** [comment]
Please test

**Comment by raveit65** [comment]
If the height of menuitems are fine i will commit that to other themes.

**Comment by flexiondotorg** [comment]
Just had a quick look and I noticed that Indicator menus are really squash together now. So and a improvement and a regression :-)

**Comment by raveit65** [comment]
What is the indicator menu?
Screenshot please.....

**Comment by flexiondotorg** [comment]
Use MATE Tweak to switch to Cupertino, Redmond, Pantheon or Mutiny. The Indicators are use for Bluetooth, Network,  Session etc. 

When you click them, menus appear. Those menus are squished.

**Comment by raveit65** [comment]
I never understood why this called indicator and not applet, maybe ubuntu wants to confuse me?
session-applet

**Comment by raveit65** [comment]
Not really sure if we talking about same gui at slack chat, as this is the normal blueman-applet menu and not a indicator.
bluetooth-indicator
And again a lot of icons are to dark for the panel, ie bluetooth icon.

**Comment by raveit65** [comment]
> When you click them, menus appear. Those menus are squished.

@flexiondotorg 
I don't see that, please post screenshot where do you see it.
I'd like to finish that.....

**Comment by flexiondotorg** [comment]
Hi,

@raveit65 This is what `master` looks like:

blueman-menu-before

This is what  `dev-menus-and-treeviews` looks like:

blueman-menu-after

**Pull request merged**
