### PR TITLE
HiDPI window controls

### PR DESCRIPTION
**Pull request by vkareh**
This adds higher resolution window controls (generated from the unity/svg files), and explicitly sets the lower resolution size in the image `<draw_ops>`. This allows marco to determine the intended size to be used for either LoDPI or HiDPI rendering.

Needs https://github.com/mate-desktop/marco/pull/561

### CODE REVIEW

**Comment by muktupavels** [comment]
Needs? How that affect other window managers that use metacity themes?

**Comment by vkareh** [comment]
This change should be compatible with the metacity window manager, as it already scales the assets based on the size specified in the theme file.

Are you aware of other window managers that use metacity theme spec apart from metacity and marco? It'd be nice to test in those as well.

**Comment by muktupavels** [comment]
Should be or is? `Needs mate-desktop/marco#561` sounds like this change depends on fixes/changes in marco...

Muffin is mutter fork that still use metacity themes.

**Comment by vkareh** [comment]
Ah, good thanks. I'll test with Muffin  later this week (although these changes are meant for MATE).

Regarding the "needs", it does on marco, otherwise the controls show up at the wrong size. Metacity is already fine, and we don't really support Muffin.

**Comment by muktupavels** [comment]
Sure you can support whatever you want with your own themes. :)

What I am worried that similar fixes might be advertised for 3rd party theme authors. What then will happen? Fix for one desktop environment will break other while in theory it is same theme, same spec... Please don't do that!

Otherwise it is time for `marco-theme-x.xml` and then you can do whatever you want.

`otherwise the controls show up at the wrong size` is indication that such thing/change in theme file is not supported... Metacity working fine with that change is good luck nothing more.

**Pull request merged**
